config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  get 'search' => 'searches#search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :index, :update] do
    get 'follows' => 'users#follow_users'
    get 'followers' => 'users#follower_users'
  end
  resources :relationships, only: [:create, :destroy] 
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end


=begin
	Prefix Verb   URI Pattern                                                                              Controller#Action
                     root GET    /                                                                                        homes#top
                    about GET    /home/about(.:format)                                                                    homes#about
                   search GET    /search(.:format)                                                                        searches#search
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
                          PUT    /users(.:format)                                                                         devise/registrations#update
                          DELETE /users(.:format)                                                                         devise/registrations#destroy
                          POST   /users(.:format)                                                                         devise/registrations#create
             user_follows GET    /users/:user_id/follows(.:format)                                                        users#follow_users
           user_followers GET    /users/:user_id/followers(.:format)                                                      users#follower_users
                    users GET    /users(.:format)                                                                         users#index
                edit_user GET    /users/:id/edit(.:format)                                                                users#edit
                     user GET    /users/:id(.:format)                                                                     users#show
                          PATCH  /users/:id(.:format)                                                                     users#update
                          PUT    /users/:id(.:format)                                                                     users#update
            relationships POST   /relationships(.:format)                                                                 relationships#create
             relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
           book_favorites DELETE /books/:book_id/favorites(.:format)                                                      favorites#destroy
                          POST   /books/:book_id/favorites(.:format)                                                      favorites#create
       book_post_comments POST   /books/:book_id/post_comments(.:format)                                                  post_comments#create
        book_post_comment DELETE /books/:book_id/post_comments/:id(.:format)                                              post_comments#destroy
                    books GET    /books(.:format)                                                                         books#index
                          POST   /books(.:format)                                                                         books#create
                edit_book GET    /books/:id/edit(.:format)                                                                books#edit
                     book GET    /books/:id(.:format)                                                                     books#show
                          PATCH  /books/:id(.:format)                                                                     books#update
                          PUT    /books/:id(.:format)                                                                     books#update
                          DELETE /books/:id(.:format)                                                                     books#destroy
               refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/refile-46b4178654e6/lib/refile/app.rb">
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
[vagrant@localhost Bookers]$ 

=end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, presence: true
  validates :name,    length: { minimum: 2 }
  validates :name,    length: { maximum: 20 }
  validates :introduction,    length: { maximum: 50 }
  #follow
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search, word)
    if search == "perfect_match"
      @usrs = User.where("name LIKE?", "#{word}")
    elsif  search == "forward_match"
      @users =User.where("name LIKE?", "%#{word}")
    elsif search == "backward_match"
      @users = User.where("name LIKE?", "#{word}%")
    elsif search == "partial_match"
      @users = User.where("name LIKE?", "%#{word}%")
    else
      @users = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books.page(params[:page]).reverse_order
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
		 redirect_to user_path(current_user.id)
		else
		end
	end	

	def create
=begin		@book = Book.new(book_params)
		if @book.save
			flash[:notice] = "You have creatad book successfully."
            redirect_to book_path(@book.id)
        else
        	render template: "book/index"
        end
=end
	end

	def index
		@user = current_user
		@book = Book.new
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
		    redirect_to user_path(@user.id)
		else 
			render :edit
	    end
	end

	def follow_users
		user = User.find(params[:user_id])
		@users = user.followings
	end

	def follower_users
		user = User.find(params[:user_id])
		@users = user.followers
	end

	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="container">
<div class="row">

<div class="sidebar col-xs-3">
	<h2>User info</h2>
  <table class="table table-sm">
    <tr>
      <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
      </th>
      <th></th>
    </tr>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to "#{user.followings.count}", user_follows_path(user) %></td>
    </tr>
    <tr>
      <td>followers</td>
      <td><%= link_to "#{user.followers.count}", user_followers_path(user) %></td>
    </tr>
    </table>
    <div class="row ">
    <% if user.id == current_user.id %>
	    <%= link_to edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" do %>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
          <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: {method: :delete}) do |f| %>
            <%= f.hidden_field :follow_id, value:user.id %>
            <%= f.submit 'フォロー外す', class: 'btn btn-danger' %>
          <% end %>
          <% else %>
          <%= form_for(current_user.relationships.build) do |f| %>
               <%= f.hidden_field :follow_id, value:user.id %>
               <%= f.submit 'フォローする', class: 'btn btn-primary'%>
          <% end %>
     <% end %>
    <% end %>
  </div>


<div class="New book">
  <h2>New book</h2>
  <% if book.errors.any? %>
      <p> error prohibited this book from being saved:</p>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

  <%= form_for(book) do |f| %>
    <div class="field row">
      <p>Title</p>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field row">
        <p>Opinion</p>
        <%= f.text_area :body,  class: "form-control"%>
    </div>
    <div class="actions row">
    <%= f.submit 'Create Book', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class="container">
<%= render 'searches/search_form'%>

<h2>User info</h2>

<% if @user.errors.any? %>
 <p> error prohibited this book from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for(@user) do |f| %>
    <label>Name</label>
    <%= f.text_field :name, autofocus: true %>
    <div class="field">
    	<label>Image</label>
        <%= f.attachment_field :profile_image %>
    </div>
    <div class="field">
    	<label>Introduction</label>
    <%= f.text_field :introduction, autofocus: true %>
    </div>
    <div class="action">            
    <%= f.submit "Update User" %>
    </div>
    
<% end %>

</div>

app/views/users/follow_users.html.erb
<h2>Follow Users</h2>
  <table class="table-hover table table-sm">
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
      	  <td></td>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td><%= link_to"Show", user_path(user.id) %></td>
      </tr>
      <% end %>
  </table>
    

app/views/users/follower_users.html.erb
<h2>Follower Users</h2>
  <table class="table-hover table table-sm">
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
     <% @users.each do |user| %>
      <tr>
      	  <td></td>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td><%= link_to"Show", user_path(user.id) %></td>
      </tr>
      <% end %>
  </table>

app/views/users/index.html.erb
	
<%= render 'users/list', user: @user, book: @book %>

<div class="Users col-xs-9">
  <%= render 'searches/search_form'%>

	<h2>Users</h2>
	<table class="table table-sm">
		<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	    </thead>
	    <tbody>
		  <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          
          <td>
<% unless current_user == user %>
     <% if current_user.following?(user) %>
          <%= form_for(current_user.relationships.find_by(follow_id: user.id),html: {method: :delete}) do |f| %>
            <%= f.hidden_field :follow_id, value:user.id %>
            <%= f.submit 'フォロー外す', class: 'btn btn-danger' %>
          <% end %>
          <% else %>
          <%= form_for(current_user.relationships.build) do |f| %>
               <%= f.hidden_field :follow_id, value:user.id %>
               <%= f.submit 'フォローする', class: 'btn btn-primary'%>
          <% end %>
     <% end %>
<% end %>
          </td>

          <td><%= link_to"Show", user_path(user.id) %></td>
        </tr>
      <% end %>
      </tbody>
	</table>
</div>

</div>
</div>

app/views/users/show.html.erb
  
<%= render 'users/list', user: @user, book:@book%>

<div class="Books-table col-xs-9">
  <%= render 'searches/search_form'%>

	<h2>Books</h2>
    <table class="table-hover table table-sm">
      <tr>
        <th></th>
        <th>Title</th>
        <th>Body</th>
        <th>いいね</th>
        <th>コメント数</th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %></td>
          <td><%= link_to"#{book.title}", book_path(book.id) %></td>
          <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
          <td><%= link_to book_favorites_path(book),method: :delete do %>
              <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
              <%= book.favorites.count %>
              <% end %>
          </td>
          <% else %>
          <td><%= link_to book_favorites_path(book),method: :post do %>
              <i class="glyphicon glyphicon-heart-empty"></i>
              <%= book.favorites.count %>
              <% end %>           
          </td>
          <% end %>
          <td><p>コメント数：</p><%= book.post_comments.count %></td>
        </tr>
      <% end %>
    </table>
</div>

</div>
</div>