config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  get 'search' => 'searches#search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :index, :update] do
    get 'follows' => 'users#follow_users'
    get 'followers' => 'users#follower_users'
  end
  resources :relationships, only: [:create, :destroy] 
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end


=begin
	Prefix Verb   URI Pattern                                                                              Controller#Action
                     root GET    /                                                                                        homes#top
                    about GET    /home/about(.:format)                                                                    homes#about
                   search GET    /search(.:format)                                                                        searches#search
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
                          PUT    /users(.:format)                                                                         devise/registrations#update
                          DELETE /users(.:format)                                                                         devise/registrations#destroy
                          POST   /users(.:format)                                                                         devise/registrations#create
             user_follows GET    /users/:user_id/follows(.:format)                                                        users#follow_users
           user_followers GET    /users/:user_id/followers(.:format)                                                      users#follower_users
                    users GET    /users(.:format)                                                                         users#index
                edit_user GET    /users/:id/edit(.:format)                                                                users#edit
                     user GET    /users/:id(.:format)                                                                     users#show
                          PATCH  /users/:id(.:format)                                                                     users#update
                          PUT    /users/:id(.:format)                                                                     users#update
            relationships POST   /relationships(.:format)                                                                 relationships#create
             relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
           book_favorites DELETE /books/:book_id/favorites(.:format)                                                      favorites#destroy
                          POST   /books/:book_id/favorites(.:format)                                                      favorites#create
       book_post_comments POST   /books/:book_id/post_comments(.:format)                                                  post_comments#create
        book_post_comment DELETE /books/:book_id/post_comments/:id(.:format)                                              post_comments#destroy
                    books GET    /books(.:format)                                                                         books#index
                          POST   /books(.:format)                                                                         books#create
                edit_book GET    /books/:id/edit(.:format)                                                                books#edit
                     book GET    /books/:id(.:format)                                                                     books#show
                          PATCH  /books/:id(.:format)                                                                     books#update
                          PUT    /books/:id(.:format)                                                                     books#update
                          DELETE /books/:id(.:format)                                                                     books#destroy
               refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/refile-46b4178654e6/lib/refile/app.rb">
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
[vagrant@localhost Bookers]$ 

=end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true
	validates :body,    length: { maximum: 200}

	def favorited_by?(user)
		self.favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
    if search == "perfect_match"
      @books = Book.where("title LIKE?", "#{word}")
    elsif  search == "forward_match"
      @books =Book.where("title LIKE?", "%#{word}")
    elsif search == "backward_match"
      @books = Book.where("title LIKE?", "#{word}%")
    elsif search == "partial_match"
      @books = Book.where("title LIKE?", "%#{word}%")
    else
      @books = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user
		@bk = Book.new
		@post_comments = @book.post_comments
		@post_comment = PostComment.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "You have creatad book successfully."
			redirect_to book_path(@book.id)
		else
			@books = Book.all
			@user = current_user
			render :index
 	    end

	end

	def edit
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
		 redirect_to books_path
		else
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."
			redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'searches/search_form'%>

  <div class="row">
<h1>Editing Book</h1>
</div>

<div class="row">
<% if @book.errors.any? %>
 <p> error prohibited this book from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for(@book) do |f| %>
<div class="form-group">
            <p>Title</p>
    <%= f.text_field :title, class: "form-control" %>
<div class="form-group">
            <p>Opinion</p>
    <%= f.text_area :body, class: "form-control" %>
<%= f.submit '編集内容を保存する', class: 'btn btn-primary btn-lg btn-block'%>
<% end %>




<p class="link">
	<%= link_to "Show", book_path(@book.id)%>
</p>
<p class="link">|</p>
<p class="link">
<%= link_to "Back", books_path%>
</p>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<%= render 'users/list', user: @user, book:@book %>

<div class="Books col-xs-9">

<%= render 'searches/search_form'%>

  <h2>Books</h2>
  <table class="table-hover table table-sm">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>いいね</th>
      <th>コメント数</th>
    </tr>
    <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to"#{book.title}", book_path(book.id) %></td>
          <td><%= book.body %></td>

        <td id = "favorites_buttons_<%= book.id %>" >
         <%= render partial: 'favorites/favorite', locals: {book: book} %>
        </td>

          <td><p>コメント数：</p><%= book.post_comments.count %></td>
        </tr>
      <% end %>
  </table>
</div>


</div>
</div>

app/views/books/show.html.erb
  
	<%= render 'users/list', user: @user, book:@bk %>

<div class="col-xs-9">
  <%= render 'searches/search_form'%>

	<h2>Book detail</h2>
	<table class="table table-sm">
        <tr>
          <td>
            
            <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %><br>
            <%= @user.name %>
            <% end %>
          </td>
            
          <td><%= link_to"#{@book.title}", book_path(@book.id) %></td>

          <td><%= @book.body %></td>
          
          <td id = "favorites_buttons_<%= @book.id %>" >
          <%= render partial: 'favorites/favorite', locals: {book: @book} %>
          </td>

          <td><p>コメント数：</p><%= @book.post_comments.count %></td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to"Edit", edit_book_path(@book.id), class: 'btn btn-success' %></td>
            <td><%= link_to"Destroy", book_path(@book.id), method: :delete, class: 'btn btn-danger' %></td>
          <% end %>


        </tr>
	</table>
  
  <div id="comments_area">
            <%= render partial: 'post_comments/index', locals: { post_comments: @post_comments, book: @book } %>
  </div>
  
   <% if user_signed_in? %>
        <div class="comment-create">
            <h3 class="text-left">レビューを投稿する</h3>
            <%= render partial: 'post_comments/form', locals: { book: @book, post_comment: @post_comment } %>
        </div>
    <% end %>

</div>

</div>
</div>